from setuptools import setup, find_packages

setup(
    name='helloagi',
    version='0.5.0',
    description='The first open-source AGI runtime with governed autonomy, evolving identity, and anticipatory intelligence.',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    author='Eng. Mohammed Mazyad Alkhaldi',
    author_email='helloagi@proton.me',
    url='https://github.com/mmsk2007/helloagi',
    license='MIT',
    package_dir={'': 'src'},
    packages=find_packages(where='src'),
    python_requires='>=3.9',
    install_requires=[
        'anthropic>=0.30',
        'anyio>=4.0',
        'croniter>=2.0',
        'requests>=2.28',
        'tzdata>=2024.1',
    ],
    extras_require={
        'rich': ['rich>=13.0'],
        'telegram': ['python-telegram-bot>=20.0'],
        'discord': ['discord.py>=2.0'],
        'embeddings': ['google-genai>=1.0'],
        'claude-sdk': ['claude-agent-sdk>=0.1'],
        'all': [
            'rich>=13.0',
            'python-telegram-bot>=20.0',
            'discord.py>=2.0',
            'google-genai>=1.0',
            'claude-agent-sdk>=0.1',
        ],
        'dev': ['pytest>=7.0', 'pytest-asyncio>=0.21'],
    },
    entry_points={
        'console_scripts': [
            'helloagi=agi_runtime.cli:main',
        ],
    },
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
    ],
    keywords='agi agent autonomous governance safety tools llm claude',
)
